repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
    args: ["--branch", "main"]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args: [--config=./pyproject.toml]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.11.0
  hooks:
  - id: black-jupyter
    args: [--config=./pyproject.toml]
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--settings-path=./pyproject.toml]
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["-r", "-x","./.venv/*","-s" ,"B101,B608,B403,B307,B105,B110,B301","."]
